# Generated by Django 5.2.7 on 2025-12-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="einvoice_enabled",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
