# Generated by Django 5.2.7 on 2025-12-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_company_einvoice_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
