# Generated by Django 5.2.7 on 2025-12-20 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="group",
            field=models.ForeignKey(
                blank=True,
                default="devaki",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.group",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(default=list),
        ),
    ]
