# Generated by Django 5.2.7 on 2025-12-20 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_group_user_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
        migrations.AddField(
            model_name="group",
            name="companies",
            field=models.ManyToManyField(related_name="groups", to="core.company"),
        ),
        migrations.AddField(
            model_name="company",
            name="organization",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="core.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="organization",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="core.organization",
            ),
            preserve_default=False,
        ),
    ]
