# Generated by Django 5.2.7 on 2025-12-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_organization_remove_company_user_group_companies_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="group",
        ),
        migrations.AddField(
            model_name="user",
            name="companies",
            field=models.ManyToManyField(related_name="users", to="core.company"),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                default="devaki",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="core.organization",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
