# Generated by Django 5.2.7 on 2026-01-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_user_group_user_companies_user_organization_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
