# Generated by Django 5.2.7 on 2026-02-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_company_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="email",
        ),
        migrations.AddField(
            model_name="company",
            name="emails",
            field=models.JSONField(default=list),
        ),
    ]
