# Generated by Django 5.2.7 on 2026-02-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_company_email_company_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="print_types",
            field=models.JSONField(default=list),
        ),
    ]
