# Generated by Django 5.2.7 on 2026-09-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_company_print_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.CharField(blank=True, db_index=True, max_length=150, null=True)),
                ('company', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(db_index=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('is_error', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'is_error'], name='core_apireq_timesta_3165c6_idx'), models.Index(fields=['user', '-timestamp'], name='core_apireq_user_03652f_idx')],
            },
        ),
    ]
