# Generated by Django 5.2.7 on 2026-02-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="doc_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ledger",
            name="moc",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ledger",
            name="notes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="ref",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
