# Generated by Django 5.2.7 on 2025-12-08 14:22

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beat",
            fields=[
                ("name", models.CharField(max_length=80)),
                (
                    "salesman_name",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "name",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Beats",
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.CharField(max_length=20)),
                ("sub_type", models.CharField(max_length=20)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "amt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("moc", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Discount",
            },
        ),
        migrations.CreateModel(
            name="Party",
            fields=[
                ("code", models.CharField(max_length=10)),
                ("master_code", models.CharField(blank=True, max_length=10, null=True)),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("type", models.CharField(db_default="shop", max_length=10)),
                ("addr", models.CharField(blank=True, max_length=150, null=True)),
                ("pincode", models.IntegerField(blank=True, null=True)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "code",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Party",
            },
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("inum", models.CharField(max_length=20)),
                ("party_id", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("amt", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("irn", models.CharField(blank=True, max_length=80, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "type",
                    models.CharField(db_default="purchase", max_length=15, null=True),
                ),
                ("ref", models.CharField(max_length=15, null=True)),
                (
                    "tds",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tcs",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "inum",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "party",
                    models.ForeignObject(
                        from_fields=("company", "party_id"),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.party",
                        to_fields=("company", "code"),
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Purchase",
            },
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                ("inum", models.CharField(max_length=20)),
                ("party_id", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("amt", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ctin", models.CharField(blank=True, max_length=20, null=True)),
                ("irn", models.CharField(blank=True, max_length=80, null=True)),
                ("gst_period", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "roundoff",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("type", models.CharField(max_length=15)),
                (
                    "tds",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "tcs",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "inum",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "party",
                    models.ForeignObject(
                        from_fields=("company", "party_id"),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.party",
                        to_fields=("company", "code"),
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales",
            },
            managers=[
                ("user_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="SalesChanges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.CharField(db_index=True, max_length=20)),
                ("field", models.CharField(max_length=20)),
                ("notes", models.CharField(blank=True, max_length=200, null=True)),
                ("old_value", models.CharField(blank=True, max_length=100, null=True)),
                ("new_value", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "sales",
                    models.ForeignObject(
                        from_fields=("company", "bill_id"),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.sales",
                        to_fields=("company", "inum"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("name", models.CharField(max_length=20)),
                ("hsn", models.CharField(max_length=20, null=True)),
                ("desc", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "rt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=1,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "standard_rate",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "name",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stock",
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                ("inum", models.CharField(max_length=20)),
                ("date", models.DateField()),
                ("godown", models.CharField(max_length=20, null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "inum",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_id", models.CharField(max_length=10)),
                ("qty", models.IntegerField()),
                (
                    "txval",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "rt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=1,
                        default=0,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "bill_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "pur_bill_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "adj_bill_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
                (
                    "purchase",
                    models.ForeignObject(
                        from_fields=("company", "pur_bill_id"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.purchase",
                        to_fields=("company", "inum"),
                    ),
                ),
                (
                    "sales",
                    models.ForeignObject(
                        from_fields=("company", "bill_id"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="erp.sales",
                        to_fields=("company", "inum"),
                    ),
                ),
                (
                    "stock",
                    models.ForeignObject(
                        from_fields=("company", "stock_id"),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="erp.stock",
                        to_fields=("company", "name"),
                    ),
                ),
                (
                    "stock_adjustment",
                    models.ForeignObject(
                        from_fields=("company", "adj_bill_id"),
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="erp.stockadjustment",
                        to_fields=("company", "inum"),
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
