# Generated by Django 5.2.7 on 2026-02-05 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sales",
            managers=[],
        ),
        migrations.DeleteModel(
            name="Beat",
        ),
    ]
