# Generated by Django 5.2.7 on 2025-12-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0006_remove_user_group_user_companies_user_organization_and_more"),
        ("report", "0009_alter_billageingreport_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("companies", models.ManyToManyField(to="core.company")),
            ],
        ),
        migrations.CreateModel(
            name="ChequeDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_id", models.CharField(max_length=15)),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("KVB 650", "KVB 650"),
                            ("SBI", "SBI"),
                            ("CANARA", "CANARA"),
                            ("BARODA", "BARODA"),
                            ("UNION BANK", "UNION BANK"),
                            ("AXIS", "AXIS"),
                            ("HDFC", "HDFC"),
                            ("CENTRAL BANK", "CENTRAL BANK"),
                            ("INDIAN BANK", "INDIAN BANK"),
                            ("IOB", "IOB"),
                            ("ICICI", "ICICI"),
                            ("CUB", "CUB"),
                            ("KOTAK", "KOTAK"),
                            ("SYNDICATE", "SYNDICATE"),
                            ("TMB", "TMB"),
                            ("UNITED BANK", "UNITED BANK"),
                            ("TCB", "TCB"),
                            ("PGB", "PGB"),
                        ],
                        max_length=100,
                    ),
                ),
                ("cheque_no", models.CharField(max_length=20)),
                ("amt", models.FloatField()),
                ("cheque_date", models.DateField()),
                ("deposit_date", models.DateField(blank=True, null=True)),
                ("entry_date", models.DateField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.company",
                    ),
                ),
                (
                    "party",
                    models.ForeignObject(
                        from_fields=("company_id", "party_id"),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="report.partyreport",
                        to_fields=("company_id", "code"),
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("idx", models.IntegerField()),
                ("ref", models.TextField(max_length=200)),
                ("desc", models.TextField(max_length=200)),
                ("amt", models.IntegerField()),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("cheque", "Cheque"),
                            ("neft", "NEFT"),
                            ("upi", "UPI (IKEA)"),
                            ("cash_deposit", "Cash Deposit"),
                            ("self_transfer", "Self Transfer"),
                            ("others", "Others"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "cheque_status",
                    models.TextField(
                        blank=True,
                        choices=[("passed", "Passed"), ("bounced", "Bounced")],
                        db_default="passed",
                        default="passed",
                        null=True,
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="bank.bank"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.company",
                    ),
                ),
                (
                    "cheque_entry",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bank_entry",
                        to="bank.chequedeposit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Bank",
                "unique_together": {("date", "idx", "bank")},
            },
        ),
        migrations.CreateModel(
            name="BankCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.CharField(max_length=15)),
                ("party_id", models.CharField(max_length=15)),
                ("amt", models.IntegerField()),
                ("pushed", models.BooleanField(db_default=False, default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.company",
                    ),
                ),
                (
                    "party",
                    models.ForeignObject(
                        from_fields=("company_id", "party_id"),
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="report.partyreport",
                        to_fields=("company_id", "code"),
                    ),
                ),
                (
                    "bank_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="bank.bankstatement",
                    ),
                ),
                (
                    "cheque_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection",
                        to="bank.chequedeposit",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("company_id", "bill_id", "cheque_entry", "bank_entry")
                },
            },
        ),
    ]
