# Generated by Django 5.2.7 on 2025-12-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
        ("core", "0006_remove_user_group_user_companies_user_organization_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankcollection",
            old_name="bill_id",
            new_name="bill",
        ),
        migrations.AlterUniqueTogether(
            name="bankcollection",
            unique_together={("company", "cheque_entry", "bank_entry")},
        ),
    ]
