# Generated by Django 5.2.7 on 2025-12-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0002_rename_bill_id_bankcollection_bill_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bankcollection",
            unique_together={("cheque_entry", "bank_entry")},
        ),
        migrations.RemoveField(
            model_name="bankcollection",
            name="company",
        ),
        migrations.RemoveField(
            model_name="bankcollection",
            name="party",
        ),
        migrations.RemoveField(
            model_name="bankcollection",
            name="party_id",
        ),
    ]
