# Generated by Django 5.2.7 on 2025-12-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0003_alter_bankcollection_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bankcollection",
            unique_together={("bill", "cheque_entry", "bank_entry")},
        ),
    ]
