# Generated by Django 5.2.7 on 2026-01-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0004_alter_bankcollection_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="account_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="bank",
            name="type",
            field=models.CharField(
                choices=[("sbi", "SBI"), ("kvb", "KVB")], default="sbi", max_length=10
            ),
        ),
    ]
