# Generated by Django 5.2.7 on 2026-01-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0005_bank_account_number_bank_type"),
        ("core", "0006_remove_user_group_user_companies_user_organization_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.company",
            ),
        ),
    ]
