# Generated by Django 5.2 on 2026-01-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0006_alter_bankstatement_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatement",
            name="statement_id",
            field=models.CharField(default="a", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bankstatement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
