# Generated by Django 5.2.7 on 2026-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0007_bankstatement_statement_id_alter_bankstatement_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankstatement",
            name="statement_id",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
