# Generated by Django 5.2.7 on 2026-01-04 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0008_alter_bankstatement_statement_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankcollection",
            name="pushed",
        ),
    ]
