# Generated by Django 5.2.7 on 2026-01-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0009_remove_bankcollection_pushed"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatement",
            name="events",
            field=models.JSONField(default=list),
        ),
    ]
