# Generated by Django 5.2.7 on 2025-12-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.TextField(blank=True, max_length=40, null=True)),
                ("print_time", models.DateTimeField(blank=True, null=True)),
                (
                    "print_type",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("first_copy", "First Copy"),
                            ("loading_sheet", "Loading Sheet"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_reloaded", models.BooleanField(db_default=False, default=False)),
                ("reason", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "loading_sheet_id",
                    models.TextField(blank=True, max_length=30, null=True),
                ),
                ("vehicle_id", models.TextField(blank=True, max_length=30, null=True)),
                ("loading_time", models.DateTimeField(blank=True, null=True)),
                ("delivered_time", models.DateTimeField(blank=True, null=True)),
                ("irn", models.TextField(blank=True, null=True)),
                ("delivered", models.BooleanField(blank=True, null=True)),
                (
                    "delivery_reason",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("scanned", "Scanned"),
                            ("bill_with_shop", "Bill With Shop"),
                            ("cash_bill_success", "Cash Bill (Collected Money)"),
                            ("bill_return", "Bill Return"),
                            ("qrcode_not_found", "QR Code Not Found"),
                            ("others", "Other Reason"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "plain_loading_sheet",
                    models.BooleanField(db_default=False, default=False),
                ),
                ("cash_bill", models.BooleanField(db_default=False, default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("status", models.IntegerField()),
                ("error", models.TextField(blank=True, max_length=100000, null=True)),
                (
                    "start_bill_no",
                    models.TextField(blank=True, max_length=10, null=True),
                ),
                ("end_bill_no", models.TextField(blank=True, max_length=10, null=True)),
                ("bill_count", models.IntegerField(blank=True, default=0, null=True)),
                ("date", models.DateField()),
                ("automatic", models.BooleanField(db_default=False, default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BillingProcessStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("process", models.TextField(max_length=30)),
                ("time", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="BillStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField(max_length=30)),
                ("count", models.TextField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.TextField(max_length=100)),
                (
                    "batch",
                    models.TextField(
                        db_default="00000", default="00000", max_length=10
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("allocated", models.IntegerField()),
                ("rate", models.FloatField()),
                ("reason", models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_no",
                    models.TextField(max_length=60, primary_key=True, serialize=False),
                ),
                ("salesman", models.TextField(max_length=30)),
                ("date", models.DateField()),
                (
                    "type",
                    models.TextField(
                        blank=True,
                        choices=[("SH", "Shikhar"), ("SE", "Salesman")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("party_id", models.TextField(max_length=30)),
                ("party_hul_code", models.TextField(max_length=40)),
                ("party_name", models.TextField(max_length=100)),
                ("beat", models.TextField(max_length=30)),
                ("place_order", models.BooleanField(db_default=False, default=False)),
                ("force_order", models.BooleanField(db_default=False, default=False)),
                ("creditlock", models.BooleanField(db_default=False, default=False)),
                ("release", models.BooleanField(db_default=False, default=False)),
                ("delete_order", models.BooleanField(db_default=False, default=False)),
            ],
            options={
                "verbose_name": "Orders",
                "verbose_name_plural": "Billing",
            },
        ),
        migrations.CreateModel(
            name="PushedCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_code", models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="SalesmanLoadingSheet",
            fields=[
                (
                    "inum",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("salesman", models.TextField(max_length=30)),
                ("party", models.TextField(blank=True, max_length=30, null=True)),
                ("beat", models.TextField(max_length=30)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "name",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("vehicle_no", models.CharField(max_length=30)),
                ("name_on_impact", models.CharField(max_length=30, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
