# Generated by Django 5.2.7 on 2025-12-08 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bill", "0001_initial"),
        ("core", "0001_initial"),
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.company"
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.company"
            ),
        ),
        migrations.AddField(
            model_name="billingprocessstatus",
            name="billing",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_status",
                to="bill.billing",
            ),
        ),
        migrations.AddField(
            model_name="billstatistics",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.company"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="billing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="bill.billing",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.company"
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="party",
            field=models.ForeignObject(
                from_fields=("company", "party_id"),
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="report.partyreport",
                to_fields=("company", "code"),
            ),
        ),
        migrations.AddField(
            model_name="orderproducts",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="bill.orders",
            ),
        ),
        migrations.AddField(
            model_name="pushedcollection",
            name="billing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection",
                to="bill.billing",
            ),
        ),
        migrations.AddField(
            model_name="salesmanloadingsheet",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.company"
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.company"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderproducts",
            unique_together={("order", "product", "batch")},
        ),
    ]
