# Generated by Django 5.2.7 on 2025-12-08 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0002_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="id",
        ),
        migrations.AddField(
            model_name="bill",
            name="pk",
            field=models.CompositePrimaryKey(
                "company",
                "bill_id",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="salesmanloadingsheet",
            name="pk",
            field=models.CompositePrimaryKey(
                "company",
                "inum",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="pk",
            field=models.CompositePrimaryKey(
                "company",
                "name",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="bill_id",
            field=models.TextField(default="DEFAULT", max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salesmanloadingsheet",
            name="inum",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("key", models.CharField(max_length=50)),
                ("status", models.BooleanField(default=False)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "key",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
