# Generated by Django 5.2.7 on 2025-12-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0003_remove_bill_id_bill_pk_salesmanloadingsheet_pk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="bill_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
