# Generated by Django 5.2.7 on 2025-12-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0004_bill_bill_date"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bill",
            unique_together={("company", "bill_id")},
        ),
        migrations.AddField(
            model_name="bill",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.RemoveField(
            model_name="bill",
            name="pk",
        ),
    ]
