# Generated by Django 5.2.7 on 2025-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0005_alter_bill_unique_together_bill_id_remove_bill_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="beat",
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="bill_amt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="party_id",
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="party_name",
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
