# Generated by Django 5.2.7 on 2025-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0006_bill_beat_bill_bill_amt_bill_party_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="ctin",
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
