# Generated by Django 5.2.7 on 2025-12-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0007_bill_ctin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
