# Generated by Django 5.2.7 on 2025-12-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0008_delete_settings"),
        ("core", "0002_company_einvoice_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billstatistics",
            name="company",
        ),
        migrations.AlterUniqueTogether(
            name="orderproducts",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="orderproducts",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="billing",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="company",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="party",
        ),
        migrations.RemoveField(
            model_name="pushedcollection",
            name="billing",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="automatic",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="bill_count",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="date",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="end_bill_no",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="error",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="id",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="start_bill_no",
        ),
        migrations.RemoveField(
            model_name="billing",
            name="start_time",
        ),
        migrations.AddField(
            model_name="billing",
            name="time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="billing",
            name="company",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="core.company",
            ),
        ),
        migrations.AlterField(
            model_name="billing",
            name="status",
            field=models.CharField(
                choices=[("getorder", "Get Order"), ("postorder", "Post Order")],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="BillingProcessStatus",
        ),
        migrations.DeleteModel(
            name="BillStatistics",
        ),
        migrations.DeleteModel(
            name="OrderProducts",
        ),
        migrations.DeleteModel(
            name="Orders",
        ),
        migrations.DeleteModel(
            name="PushedCollection",
        ),
    ]
