# Generated by Django 5.2.7 on 2025-12-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0009_remove_billstatistics_company_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="market_order_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="order_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
