# Generated by Django 5.2.7 on 2025-12-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0010_billing_market_order_data_billing_order_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="status",
            new_name="process",
        ),
        migrations.AddField(
            model_name="billing",
            name="ongoing",
            field=models.BooleanField(default=False),
        ),
    ]
