# Generated by Django 5.2.7 on 2025-12-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0011_rename_status_billing_process_billing_ongoing"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="order_hash",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
