# Generated by Django 5.2.7 on 2025-12-18 21:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0012_billing_order_hash"),
        ("core", "0002_company_einvoice_enabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.company"
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="billing",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="order_values",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="billing",
            name="pushed_collections",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name="billing",
            unique_together={("company", "date")},
        ),
    ]
