# Generated by Django 5.2.7 on 2025-12-19 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0013_billing_date_billing_id_billing_order_values_and_more"),
        ("core", "0002_company_einvoice_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_id", models.CharField(max_length=30)),
                ("bills", models.IntegerField(default=1)),
                ("days", models.IntegerField(default=0)),
                ("value", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "party_id")},
            },
        ),
    ]
