# Generated by Django 5.2.7 on 2025-12-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0014_partycredit"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="user",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
