# Generated by Django 5.2.7 on 2025-12-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0015_billing_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="last_bills",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
