# Generated by Django 5.2.7 on 2025-12-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0016_billing_last_bills"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="stop",
            field=models.BooleanField(default=False),
        ),
    ]
