# Generated by Django 5.2 on 2025-12-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0017_billing_stop"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="pushed_collections",
        ),
    ]
