# Generated by Django 5.2.7 on 2026-01-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0018_remove_billing_pushed_collections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="pk",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
