# Generated by Django 5.2.7 on 2026-01-24 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0019_remove_vehicle_pk_vehicle_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="vehicle_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bill.vehicle",
            ),
        ),
    ]
