# Generated by Django 5.2.7 on 2026-01-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0020_alter_bill_vehicle_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="vehicle_id",
            new_name="vehicle",
        ),
    ]
