# Generated by Django 5.2.7 on 2026-01-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0021_rename_vehicle_id_bill_vehicle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="delivered_time",
            new_name="delivery_time",
        ),
    ]
