# Generated by Django 5.2.7 on 2026-01-26 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0022_rename_delivered_time_bill_delivery_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bill.vehicle",
            ),
        ),
    ]
