# Generated by Django 5.2.7 on 2026-01-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0023_alter_bill_vehicle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="delivered",
        ),
        migrations.RemoveField(
            model_name="bill",
            name="delivery_reason",
        ),
        migrations.AddField(
            model_name="bill",
            name="notes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
