# Generated by Django 5.2.7 on 2026-01-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0024_remove_bill_delivered_remove_bill_delivery_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="should_deliver",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
