# Generated by Django 5.2.7 on 2026-01-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0025_bill_should_deliver"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="should_deliver",
            new_name="delivery_applicable",
        ),
    ]
