# Generated by Django 5.2.7 on 2026-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bill", "0026_rename_should_deliver_bill_delivery_applicable"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="ewb_no",
            field=models.TextField(blank=True, null=True),
        ),
    ]
