# Generated by Django 5.2.7 on 2025-12-08 14:22

import django.db.models.deletion
import typing
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection_ref",
                    models.CharField(max_length=15, verbose_name="Collection Ref"),
                ),
                ("inum", models.CharField(max_length=15, verbose_name="BillRefNo")),
                ("date", models.DateField(verbose_name="Collection Date")),
                ("bill_date", models.DateField(verbose_name="Bill Date")),
                (
                    "party_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Party Name"
                    ),
                ),
                ("mode", models.CharField(max_length=50, verbose_name="Mode")),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "bank_entry_id",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Bank Entry ID"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "collection_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="DmgShtReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inum",
                    models.CharField(max_length=100, verbose_name="Damage Invoice No"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("damage", "damage"), ("shortage", "shortage")],
                        max_length=50,
                        verbose_name="Type (Damage or Shortage)",
                    ),
                ),
                (
                    "return_from",
                    models.CharField(
                        choices=[("market", "market"), ("rs", "rs")],
                        max_length=100,
                        verbose_name="Return From (Market/RS)",
                    ),
                ),
                ("date", models.DateField(verbose_name="Damage Date")),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Retailer Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Retailer Name"
                    ),
                ),
                (
                    "stock_id",
                    models.CharField(max_length=50, verbose_name="Product Code"),
                ),
                (
                    "desc",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Product Name"
                    ),
                ),
                ("qty", models.IntegerField(verbose_name="Quantity")),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total TUR Value"
                    ),
                ),
                (
                    "plg",
                    models.CharField(
                        max_length=100, null=True, verbose_name="PLG (DETS,FNB,..)"
                    ),
                ),
                (
                    "credit_note_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Credit Note No"
                    ),
                ),
                (
                    "original_invoice_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Original Invoice No"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "dmgsht_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="GSTR1Portal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(max_length=6, verbose_name="Period (MMYYYY)"),
                ),
                ("date", models.DateField(verbose_name="Invoice Date")),
                ("inum", models.CharField(max_length=30, verbose_name="Invoice No")),
                (
                    "type",
                    models.CharField(max_length=10, verbose_name="Type (b2b/cdnr)"),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN of Recipient"
                    ),
                ),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Invoice Amount"
                    ),
                ),
                (
                    "txval",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Taxable Value"
                    ),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - Central Tax",
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - State/UT Tax",
                    ),
                ),
                ("irn", models.CharField(max_length=80, null=True, verbose_name="IRN")),
                ("irn_date", models.DateField(null=True, verbose_name="IRN Date")),
                (
                    "srctype",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Source Type (E-Invoice)"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gstr1_portal",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="IkeaGSTR1Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=30, verbose_name="Invoice No")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "txval",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="Taxable Value"
                    ),
                ),
                ("stock_id", models.CharField(max_length=50, verbose_name="UQC")),
                ("qty", models.IntegerField(verbose_name="Quantity")),
                (
                    "rt",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=12,
                        verbose_name="Tax - Central Tax",
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                ("hsn", models.CharField(max_length=50, verbose_name="HSN")),
                (
                    "desc",
                    models.CharField(
                        max_length=255, null=True, verbose_name="HSN Description"
                    ),
                ),
                (
                    "credit_note_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Debit/Credit No"
                    ),
                ),
                (
                    "original_invoice_no",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Original Invoice No"
                    ),
                ),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Outlet Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Outlet Name"
                    ),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN of Recipient"
                    ),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - Central Tax",
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=3,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount - State/UT Tax",
                    ),
                ),
                (
                    "inv_amt",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        verbose_name="Total Invoice Amount",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "ikea_gstr1_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="OutstandingReport",
            fields=[
                (
                    "party_id",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Party Code"
                    ),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Party Name"
                    ),
                ),
                (
                    "inum",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("beat", models.CharField(max_length=40, null=True)),
                ("bill_date", models.DateField()),
                ("bill_amt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salesman", models.CharField(max_length=40, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="PartyReport",
            fields=[
                ("code", models.CharField(max_length=10, verbose_name="Party Code")),
                (
                    "master_code",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Party Master Code"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Party Name"
                    ),
                ),
                (
                    "addr",
                    models.CharField(max_length=150, null=True, verbose_name="Address"),
                ),
                (
                    "beat",
                    models.CharField(max_length=80, null=True, verbose_name="Beat"),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="GSTIN Number"
                    ),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, null=True, verbose_name="Phone"),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "company",
                        "code",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "party_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="SalesRegisterReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=100, verbose_name="BillRefNo")),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "party_id",
                    models.CharField(max_length=100, verbose_name="Party Code"),
                ),
                (
                    "party_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Party Name"
                    ),
                ),
                ("type", models.CharField(max_length=50, verbose_name="Type")),
                (
                    "amt",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Bill Amount + Credit Adjustment",
                    ),
                ),
                (
                    "ctin",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Party GSTIN"
                    ),
                ),
                (
                    "tcs",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="TCS Amt",
                    ),
                ),
                (
                    "tds",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="TDS-194R Amt",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Net Tax"
                    ),
                ),
                (
                    "schdisc",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="SchDisc",
                    ),
                ),
                (
                    "cashdisc",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="CashDisc",
                    ),
                ),
                (
                    "btpr",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="BTPR SchDisc",
                    ),
                ),
                (
                    "outpyt",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="OutPyt Adj",
                    ),
                ),
                (
                    "ushop",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Ushop Redemption",
                    ),
                ),
                (
                    "pecom",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Adjustments",
                    ),
                ),
                (
                    "roundoff",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="RoundOff",
                    ),
                ),
                (
                    "other_discount",
                    models.DecimalField(
                        blank=True,
                        db_default=Decimal("0.00"),
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Other Discount (DisFinAdj + ReversedPayout)",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "salesregister_report",
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name="StockHsnRateReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_id",
                    models.CharField(max_length=8, verbose_name="Product Code"),
                ),
                ("hsn", models.CharField(max_length=8, verbose_name="HSN")),
                (
                    "rt",
                    models.DecimalField(
                        decimal_places=1, max_digits=12, verbose_name="Tax Rate"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "stockhsnrate_report",
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
