# Generated by Django 5.2.7 on 2025-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesregisterreport",
            name="beat",
            field=models.CharField(max_length=100, null=True, verbose_name="Beat"),
        ),
    ]
