# Generated by Django 5.2.7 on 2025-12-09 17:30

import django.db.models.deletion
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("report", "0002_salesregisterreport_beat"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeatReport",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=40)),
                ("salesman_id", models.IntegerField()),
                ("salesman_code", models.CharField(max_length=30)),
                ("salesman_name", models.TextField(max_length=40)),
                ("days", models.TextField(max_length=40)),
                ("plg", models.TextField(max_length=15)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
