# Generated by Django 5.2.7 on 2025-12-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0003_beatreport"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="beatreport",
            table="beat_report",
        ),
    ]
