# Generated by Django 5.2.7 on 2025-12-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0005_reportsynclog"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportsynclog",
            name="identifier",
            field=models.CharField(default="default", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="reportsynclog",
            unique_together={("report_name", "identifier")},
        ),
        migrations.RemoveField(
            model_name="reportsynclog",
            name="company",
        ),
        migrations.RemoveField(
            model_name="reportsynclog",
            name="user",
        ),
    ]
