# Generated by Django 5.2.7 on 2025-12-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0006_alter_reportsynclog_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="beatreport",
            name="beat_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="beatreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
