# Generated by Django 5.2.7 on 2025-12-19 19:55

import django.db.models.deletion
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_company_einvoice_enabled"),
        ("report", "0007_beatreport_beat_id_alter_beatreport_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillAgeingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inum", models.CharField(max_length=20)),
                (
                    "party_name",
                    models.CharField(max_length=100, verbose_name="Party Name"),
                ),
                ("bill_amt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("collected", models.BooleanField()),
                ("days", models.IntegerField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
