# Generated by Django 5.2.7 on 2025-12-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0008_billageingreport"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="billageingreport",
            table="bill_ageing_report",
        ),
        migrations.AlterModelTable(
            name="outstandingreport",
            table="outstanding_report",
        ),
    ]
