# Generated by Django 5.2.7 on 2025-12-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0009_alter_billageingreport_table_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outstandingreport",
            name="inum",
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name="outstandingreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        )
    ]
