# Generated by Django 5.2.7 on 2025-12-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0010_outstandingreport_id_alter_outstandingreport_inum"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="outstandingreport",
            unique_together={("inum", "party_id")},
        ),
    ]
