# Generated by Django 5.2.7 on 2026-01-21 18:02

import django.db.models.deletion
import typing
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_user_group_user_companies_user_organization_and_more"),
        ("report", "0011_alter_outstandingreport_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division", models.CharField(max_length=10, verbose_name="Division")),
                ("basepack", models.IntegerField(verbose_name="Basepack")),
                ("stock_id", models.CharField(max_length=10, verbose_name="Stock ID")),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("hsn", models.CharField(max_length=10, verbose_name="HSN")),
                (
                    "hsn_description",
                    models.CharField(max_length=50, verbose_name="HSN Description"),
                ),
                ("godown", models.CharField(max_length=10, verbose_name="Godown")),
                ("pkm", models.CharField(max_length=10, verbose_name="PKM")),
                (
                    "batch_code",
                    models.CharField(max_length=10, verbose_name="Batch Code"),
                ),
                (
                    "expiry_month",
                    models.CharField(max_length=10, verbose_name="Expiry Month"),
                ),
                (
                    "expiry_date",
                    models.CharField(max_length=10, verbose_name="Expiry Date"),
                ),
                (
                    "no_of_days_to_expire",
                    models.CharField(
                        max_length=10, verbose_name="No of Days to Expire"
                    ),
                ),
                ("upc", models.CharField(max_length=10, verbose_name="UPC")),
                ("units", models.CharField(max_length=10, verbose_name="Units")),
                (
                    "stock_in_days",
                    models.CharField(max_length=10, verbose_name="Stock in Days"),
                ),
                ("pur_rate", models.CharField(max_length=10, verbose_name="Pur Rate")),
                ("rt", models.CharField(max_length=10, verbose_name="RT")),
                ("mrp", models.CharField(max_length=10, verbose_name="MRP")),
                ("value", models.CharField(max_length=10, verbose_name="Value")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.company"
                    ),
                ),
            ],
            options={
                "db_table": "stock_report",
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
