# Generated by Django 5.2.7 on 2026-01-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0012_stockreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockreport",
            name="expiry_month",
        ),
        migrations.RemoveField(
            model_name="stockreport",
            name="hsn_description",
        ),
        migrations.RemoveField(
            model_name="stockreport",
            name="no_of_days_to_expire",
        ),
        migrations.RemoveField(
            model_name="stockreport",
            name="units",
        ),
        migrations.AddField(
            model_name="stockreport",
            name="qty",
            field=models.IntegerField(default=0, verbose_name="Qty"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stockreport",
            name="expiry_date",
            field=models.DateField(verbose_name="Expiry Date"),
        ),
        migrations.AlterField(
            model_name="stockreport",
            name="mrp",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="stockreport",
            name="pur_rate",
            field=models.FloatField(verbose_name="Pur Rate"),
        ),
        migrations.AlterField(
            model_name="stockreport",
            name="rt",
            field=models.FloatField(verbose_name="GST Rate"),
        ),
        migrations.AlterField(
            model_name="stockreport",
            name="stock_id",
            field=models.CharField(max_length=15, verbose_name="Stock ID"),
        ),
        migrations.AlterField(
            model_name="stockreport",
            name="stock_in_days",
            field=models.IntegerField(null=True, verbose_name="Stock In Days"),
        ),
        migrations.AlterField(
            model_name="stockreport",
            name="upc",
            field=models.IntegerField(verbose_name="UPC"),
        ),
        migrations.AlterField(
            model_name="stockreport",
            name="value",
            field=models.FloatField(verbose_name="Value"),
        ),
    ]
