# Generated by Django 5.2.7 on 2026-01-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0013_remove_stockreport_expiry_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockreport",
            name="stock_in_days",
            field=models.CharField(null=True, verbose_name="Stock In Days"),
        ),
    ]
