# Generated by Django 5.2.7 on 2026-01-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0014_alter_stockreport_stock_in_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockreport",
            name="stock_in_days",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Stock In Days"
            ),
        ),
    ]
