# Generated by Django 5.2.7 on 2026-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0015_alter_stockreport_stock_in_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockreport",
            name="batch_code",
            field=models.CharField(max_length=20, verbose_name="Batch Code"),
        ),
        migrations.AlterField(
            model_name="stockreport",
            name="godown",
            field=models.CharField(max_length=20, verbose_name="Godown"),
        ),
    ]
