# Generated by Django 5.2.7 on 2026-02-05 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_company_email_company_emails"),
        ("report", "0016_alter_stockreport_batch_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gstr1portal",
            name="user",
        ),
        migrations.AddField(
            model_name="gstr1portal",
            name="organization",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
            preserve_default=False,
        ),
    ]
