# Generated by Django 5.2.7 on 2026-02-07 15:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0017_remove_gstr1portal_user_gstr1portal_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesregisterreport",
            name="shikar_discount",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Shikar Discount",
            ),
        ),
    ]
