# Generated by Django 5.2.7 on 2026-02-07 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0018_salesregisterreport_shikar_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesregisterreport",
            old_name="shikar_discount",
            new_name="shikhar_scheme",
        ),
    ]
