# Generated by Django 5.2.7 on 2026-02-09 18:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0019_rename_shikar_discount_salesregisterreport_shikhar_scheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesregisterreport",
            name="shikhar_scheme",
            field=models.DecimalField(
                blank=True,
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Shikar Scheme",
            ),
        ),
    ]
