# Generated by Django 5.2.7 on 2026-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0020_alter_salesregisterreport_shikhar_scheme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partyreport",
            name="beat",
            field=models.CharField(max_length=150, null=True, verbose_name="Beat"),
        ),
    ]
