# Generated by Django 5.2.7 on 2026-01-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("load", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="truckload",
            name="scanned",
            field=models.JSONField(default=list),
        ),
    ]
