# Generated by Django 5.2.7 on 2026-01-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_company_email"),
        ("load", "0002_alter_truckload_scanned"),
    ]

    operations = [
        migrations.RenameField(
            model_name="truckload",
            old_name="purchase",
            new_name="purchase_products",
        ),
        migrations.RenameField(
            model_name="truckload",
            old_name="scanned",
            new_name="scanned_products",
        ),
        migrations.AddField(
            model_name="truckload",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="truckload",
            name="organization",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.organization",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="truckload",
            name="purchase_inums",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="truckload",
            name="sku_map",
            field=models.JSONField(default=dict),
        ),
    ]
