# Generated by Django 5.2.7 on 2026-02-13 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_remove_company_email_company_emails"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_no", models.CharField(max_length=255)),
                ("company_id", models.IntegerField()),
                ("bill_date", models.DateField(blank=True, null=True)),
                ("bill_products", models.JSONField(default=dict)),
                ("scanned_products", models.JSONField(default=list)),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("bill_no", "company_id")},
            },
        ),
    ]
