# Generated by Django 5.2.7 on 2026-02-14 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_company_email_company_emails"),
        ("product_scan", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesscan",
            name="company_id",
        ),
        migrations.RemoveField(
            model_name="salesscan",
            name="organization",
        ),
        migrations.AddField(
            model_name="salesscan",
            name="company",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="core.company",
            ),
            preserve_default=False,
        ),
    ]
