# Generated by Django 5.2.7 on 2026-02-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_scan", "0002_remove_salesscan_company_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barcode",
            fields=[
                (
                    "barcode",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("basepack", models.CharField(max_length=255)),
            ],
        ),
    ]
