# Generated by Django 5.2.7 on 2026-02-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_scan", "0003_barcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="barcode",
            name="manual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesscan",
            name="logs",
            field=models.JSONField(default=list),
        ),
    ]
