# Generated by Django 5.2.7 on 2026-02-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_scan", "0004_barcode_manual_salesscan_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesscan",
            name="is_posted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="salesscan",
            name="party_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
