# Generated by Django 5.2.7 on 2026-02-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_scan", "0005_salesscan_is_posted_salesscan_party_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesscan",
            name="scanned_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
