# Generated by Django 5.2.7 on 2026-03-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_scan", "0006_salesscan_scanned_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesscan",
            name="video_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesscan",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="scan_videos/"),
        ),
        migrations.AddField(
            model_name="salesscan",
            name="video_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesscan",
            name="video_status",
            field=models.CharField(default="none", max_length=20),
        ),
    ]
