# Generated by Django 5.2.7 on 2026-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_scan", "0007_salesscan_video_end_time_salesscan_video_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesscan",
            name="processed_video",
            field=models.FileField(
                blank=True, null=True, upload_to="processed_videos/"
            ),
        ),
    ]
