# Generated by Django 5.2.7 on 2026-03-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_scan", "0008_salesscan_processed_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="salesscan",
            name="processed_video",
        ),
    ]
